#!/usr/bin/env bash

set -o errexit
set -o nounset

# Get own dir, resolve relative path if needed
ROOT=$(dirname $(readlink $0 || echo $0))
if [[ $ROOT == ../* ]]; then
  ROOT=$(cd "$(dirname $0)/$ROOT"; pwd);
fi
LIB="$ROOT/lib"

VERSION="0.0.1"

# -----------------------------------------------------------------------------

source $LIB/utils.sh
source $LIB/boot.sh
source $LIB/colors.sh

for command in $ROOT/commands/*; do
  source $command
done

# -----------------------------------------------------------------------------

usage () {
  echo "
  $(_echo gray reverse " porter v$VERSION ")

  Usage:
    porter $(_echo yellow bold install) $(_echo gray package_name)
    porter $(_echo cyan bold uninstall) $(_echo gray package_name)
    porter $(_echo green bold search) $(_echo gray string)
    porter $(_echo blue bold list)
    porter $(_echo purple bold link)
    porter $(_echo purple bold publish)

  $(_echo blue underline http://github.com/ricardobeat/porter)
  "
}

ACTION=${1:-"help"}
ARGS="${@:2}"

validate_arguments () {
  if [[ -z $ARGS ]]; then
    die "$(_echo gray Usage:) $(_echo white porter $ACTION $(_echo yellow name))"
  fi
}

case $ACTION in

  install)
    validate_args
    do_install $2
    ;;

  uninstall|remove)
    validate_args
    do_uninstall $2
    ;;

  search)
    validate_args
    do_search $2
    ;;

  list)
    do_list
    ;;

  link)
    validate_args
    do_link
    ;;

  publish)
    validate_args
    do_publish
    ;;

  help|--help|*)
    usage
    ;;

esac
